import { createSignal } from "solid-js";
import {
  BUILTIN_THEMES,
  DEFAULT_THEME,
  base16ToTheme,
  themeFromBase16,
  findBuiltinTheme,
  themeToCssVars,
  themeToXterm,
  type Theme,
} from "../lib/theme";
import { setTerminalTheme } from "../lib/terminal-registry";
import { publishStoreChange, registerStoreSync } from "../lib/store-sync";
import base16Schemes from "../data/base16-schemes.json";

// The bundled base16 gallery (src/data/base16-schemes.json, generated by
// scripts/fetch-base16-schemes.mjs). Each entry is a base16 palette; we convert
// to Theme lazily and memoize, since most sessions never open the gallery.
interface SchemeEntry {
  slug: string;
  name: string;
  variant: string | null;
  colors: Record<string, string>;
}

let galleryCache: Theme[] | null = null;

export function galleryThemes(): Theme[] {
  if (galleryCache) return galleryCache;
  galleryCache = (base16Schemes as SchemeEntry[])
    .map((s) => themeFromBase16(s.colors, { id: `gallery-${s.slug}`, name: s.name }))
    .filter((t): t is Theme => t !== null);
  return galleryCache;
}

// Active-theme store: owns the selected theme and any user-imported (base16)
// themes, persists both to localStorage, and applies the active theme to its
// two surfaces — the CSS variables on :root (app chrome) and every live xterm
// terminal (via terminal-registry). Mirrors the shape of stores/settings.ts.

const STORAGE_KEY = "specterm.theme";

interface PersistedTheme {
  activeId: string;
  customThemes: Theme[];
}

function load(): PersistedTheme {
  const fallback: PersistedTheme = { activeId: DEFAULT_THEME.id, customThemes: [] };
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) return fallback;
    const parsed = JSON.parse(raw);
    return {
      activeId: typeof parsed?.activeId === "string" ? parsed.activeId : DEFAULT_THEME.id,
      customThemes: Array.isArray(parsed?.customThemes) ? parsed.customThemes : [],
    };
  } catch {
    return fallback;
  }
}

const initial = load();

const [customThemes, setCustomThemes] = createSignal<Theme[]>(initial.customThemes);

// Every theme the picker offers: built-ins first, then imported ones.
export function availableThemes(): Theme[] {
  return [...BUILTIN_THEMES, ...customThemes()];
}

function resolve(id: string): Theme {
  return (
    findBuiltinTheme(id) ??
    customThemes().find((t) => t.id === id) ??
    (id.startsWith("gallery-") ? galleryThemes().find((t) => t.id === id) : undefined) ??
    DEFAULT_THEME
  );
}

const [activeTheme, setActiveThemeSignal] = createSignal<Theme>(resolve(initial.activeId));

export { activeTheme, customThemes };

export function activeThemeId(): string {
  return activeTheme().id;
}

function persist() {
  try {
    localStorage.setItem(
      STORAGE_KEY,
      JSON.stringify({ activeId: activeTheme().id, customThemes: customThemes() })
    );
  } catch {
    // localStorage unavailable — the choice just won't survive this session.
  }
  // Every other window holds its own copy of the theme; tell them to re-read.
  publishStoreChange("theme");
}

// Push the active theme to both surfaces: CSS variables on :root drive the app
// chrome; setTerminalTheme repaints every open terminal.
function applyActiveTheme() {
  const theme = activeTheme();
  const vars = themeToCssVars(theme);
  const root = document.documentElement.style;
  for (const [name, value] of Object.entries(vars)) {
    root.setProperty(name, value);
  }
  // Lets stylesheets (and the OS form controls via color-scheme) adapt to a
  // light vs dark theme without inspecting individual colors.
  root.setProperty("color-scheme", theme.type);
  setTerminalTheme(themeToXterm(theme));
}

export function setActiveTheme(id: string) {
  setActiveThemeSignal(resolve(id));
  applyActiveTheme();
  persist();
}

// Parse a base16/tinted-theming scheme (YAML or JSON) into a theme, store it,
// and switch to it. Returns the imported theme, or null if the text isn't a
// valid 16-color scheme. A re-import of the same name replaces the prior one.
export function importBase16Theme(text: string): Theme | null {
  const theme = base16ToTheme(text);
  if (!theme) return null;
  setCustomThemes([...customThemes().filter((t) => t.id !== theme.id), theme]);
  setActiveTheme(theme.id);
  return theme;
}

export function removeCustomTheme(id: string) {
  setCustomThemes(customThemes().filter((t) => t.id !== id));
  // If the removed theme was active, fall back to the default.
  if (!findBuiltinTheme(activeTheme().id) && !customThemes().some((t) => t.id === activeTheme().id)) {
    setActiveTheme(DEFAULT_THEME.id);
  } else {
    persist();
  }
}

// Pull the stored theme back in after another window changed it, and repaint.
function reloadFromStorage() {
  const p = load();
  setCustomThemes(p.customThemes);
  setActiveThemeSignal(resolve(p.activeId));
  applyActiveTheme();
}

// Apply the persisted theme to the DOM once at startup. Called from App's
// onMount, alongside initSettings.
export function initTheme() {
  registerStoreSync("theme", reloadFromStorage);
  applyActiveTheme();
}
